#!/usr/bin/env python3
"""reflectgen.py — Assisi Reflection Code Generator (CLI entry point)

Scans C++ headers for ACOMP/AFIELD annotations and emits .generated.cpp files
that register each component with Assisi::Core::Reflect::ComponentRegistry.

Usage:
    python reflectgen.py <header> [<header> ...] --outdir <dir> [--include <path>]

    <header>         Absolute or relative path to the source header.
    --outdir <dir>   Directory to write .generated.cpp files into.
    --include <path> Override the #include path written into generated files.
                     If omitted, auto-detected from the 'include/' segment in
                     the header path (e.g. '.../include/Assisi/Foo/Bar.hpp'
                     becomes 'Assisi/Foo/Bar.hpp').

The implementation is split across three sibling modules; this file is the CLI
plus a stable facade that re-exports their public surface so `import reflectgen`
keeps working for callers and tests:

    reflect_types    the C++ type -> codegen mapping (TYPES, TypeCodegen, ...)
    reflect_parser   header scanning + the parse-time data model
    reflect_codegen  emission of the .generated.cpp registration code
"""

import sys
import argparse
from pathlib import Path

# Re-export the public surface so `reflectgen.X` resolves for every existing
# caller and the test-suite (which reaches in for parse_header, generate_cpp,
# the dataclasses, UNSUPPORTED_TYPES, _check_unsupported, _detect_include_path).
from reflect_types import (  # noqa: F401
    TypeCodegen,
    TYPES,
    UNSUPPORTED_TYPES,
    _ASSET_ID_TYPES,
    _ENTITY_REF_TYPES,
)
from reflect_parser import (  # noqa: F401
    AnnotArgs,
    EnumInfo,
    RadioInfo,
    FieldInfo,
    ComponentInfo,
    MessageInfo,
    HandlerInfo,
    parse_header,
    parse_header_full,
    parse_annot_args,
    parse_amsg_args,
    parse_radio_spec,
    parse_enum_constants,
    find_handlers,
    find_systems,
    parse_header_systems,
    SystemInfo,
    strip_comments,
    _detect_include_path,
)
import reflect_codegen  # noqa: F401
from reflect_codegen import (  # noqa: F401
    gen_message_forward,
    gen_message_traits,
    generate_cpp,
    _check_unsupported,
    _check_asset_fields,
    _check_replication,
    _field_tc,
    NUMERIC_BOUND_RANGES,
)


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────

def count_replicable(headers) -> int:
    """How many ACOMP(replicable) component types exist across @p headers.

    A whole-tree question asked once, unlike the per-header code generation
    everywhere else here: the answer sizes ComponentMask, the exclusion bitset on
    the Replicated marker, whose bit index is a component's ordinal among the
    replicable types. Sizing it from an actual count rather than a configured
    ceiling is what keeps that a detail nobody has to know about.

    Deliberately tolerant of headers it cannot parse: a malformed one is already
    a hard error in the per-header pass, and duplicating that failure here would
    only bury the real message under a second, worse-located one.
    """
    total = 0
    for header in headers:
        try:
            components = parse_header(Path(header).resolve())
        except Exception:
            continue
        total += sum(1 for c in components
                     if c.args.has('replicable') and not c.is_asset and not c.args.has('transient'))
    return total


def render_replicable_limits(count: int) -> str:
    """The generated header that fixes ComponentMask's width."""
    mask_bytes = max(1, (count + 7) // 8)
    return f"""\
/* Generated by reflectgen. Do not edit. */
#pragma once

/// @file ReplicableLimits.hpp
/// @brief How wide a ComponentMask must be, counted from the tree at build time.
///
/// The count is of ACOMP(replicable) component types across every header routed
/// through assisi_reflect(). It sizes the exclusion bitset on NetSync's
/// Replicated marker, whose bit index is a component's ordinal among the
/// replicable types (ComponentRegistry::ReplicableOrdinalOf).
///
/// Byte granularity, so a worst case wastes seven bits rather than sixty-three,
/// and so the value only *changes* on a byte boundary — the build wraps this in
/// copy_if_different, which means most header edits regenerate an identical file
/// and rebuild nothing.
///
/// Nothing here ever reaches a file or a socket: masks serialize as arrays of
/// component *names*, on disk and on the wire alike. Widening this is therefore
/// a recompile and never a migration.

#include <cstddef>

namespace Assisi::Core::Reflect
{{

/// ACOMP(replicable) component types found in this build.
inline constexpr std::size_t kReplicableComponentCount = {count};

/// Bytes a ComponentMask needs to hold one bit per the above. At least one, so
/// a build with no replicable components still yields a valid array.
inline constexpr std::size_t kReplicableMaskBytes = {mask_bytes};

}} // namespace Assisi::Core::Reflect
"""


def _resolve_message_type(handler, messages_by_fqn: dict, header_name: str) -> str:
    """The fully-qualified, ::-anchored spelling of the message a handler takes.

    Resolved *here* rather than left to C++ name lookup, because the generated
    table lives in its own translation unit at global scope where the handler's
    enclosing namespaces are not in scope — and because leaving it to lookup is
    exactly how the wrong function gets called when two namespaces declare the
    same struct name. Anything that cannot be resolved to exactly one message is
    a build error naming the candidates, never a guess.
    """
    written = handler.message.lstrip(':')

    # Already qualified enough to name exactly one message.
    exact = [fqn for fqn in messages_by_fqn if fqn == written or fqn.endswith('::' + written)]
    if len(exact) == 1:
        return '::' + exact[0]

    if not exact:
        raise ValueError(
            f"{header_name}: handler '{handler.name}' takes 'const {handler.message} &', which names no "
            f"AMSG message type. Known messages: {sorted(messages_by_fqn) or '(none)'}.")

    # Several candidates. The handler's own namespace decides, if it can — a
    # handler declared inside a namespace that holds one of them is naming that
    # one, by the same rule C++ would use.
    scope = '::'.join(handler.namespaces)
    enclosing = [fqn for fqn in exact
                 if scope and (fqn.startswith(scope + '::') or fqn == scope + '::' + written)]
    if len(enclosing) == 1:
        return '::' + enclosing[0]

    raise ValueError(
        f"{header_name}: handler '{handler.name}' takes 'const {handler.message} &', which is ambiguous "
        f"between {sorted(exact)}. Spell the message type fully qualified in the declaration — a handler "
        f"binding must never depend on which one a name-lookup happens to find.")


def collect_messages_and_handlers(headers) -> tuple[dict, list]:
    """Scan the whole tree once: every AMSG type, and every AMSG_HANDLER.

    Tolerant of headers it cannot parse, exactly as count_replicable is and for
    the same reason: a malformed header is already a hard error in the per-header
    pass, and repeating the failure here would bury the real message.
    """
    messages_by_fqn: dict = {}
    handlers: list = []
    for header in headers:
        try:
            _, messages, found = parse_header_full(Path(header).resolve())
        except Exception:
            continue
        for msg in messages:
            messages_by_fqn[msg.fqn] = (msg, str(header))
        handlers.extend(found)
    return messages_by_fqn, handlers


def render_message_traits(headers) -> str:
    """The generated header giving every AMSG type its compile-time facts.

    Whole-tree because a trait specialization is only useful where the *call*
    is, and a call can be anywhere. Forward declarations rather than includes:
    specializing on an incomplete type is legal, and pulling in the real headers
    would close a cycle — a header declaring handlers already includes the
    dispatch header this one is part of.
    """
    messages_by_fqn, _ = collect_messages_and_handlers(headers)

    ordered = [msg for _, (msg, _header) in sorted(messages_by_fqn.items())]
    forwards = '\n'.join(gen_message_forward(msg) for msg in ordered)
    body = ''.join(gen_message_traits(msg) for msg in ordered) or \
        '// No AMSG declarations in this build.\n'

    return f"""\
/* Generated by reflectgen. Do not edit. */
#pragma once

/// @file MessageTraits.hpp
/// @brief Every AMSG type's direction, reliability, and independence, as
/// constants a template can read.
///
/// This is what turns "you sent an event from a client" into a compile error at
/// the send site instead of a dropped packet at the receive site, and what makes
/// handing a send call a struct that was never declared a message fail with an
/// incomplete type rather than silently encoding nothing.
///
/// Message types are *forward-declared* here, never included. Specializing on
/// an incomplete type is legal, and including the real headers would close a
/// cycle: a header that declares handlers already includes
/// Assisi/NetSync/MessageDispatch.hpp, which includes this.
///
/// Consequence worth knowing: a message declared inside a class rather than at
/// namespace scope cannot be forward-declared this way. AMSG is a
/// namespace-scope annotation for exactly that reason.

#include <Assisi/Core/Reflect/MessageMeta.hpp>

// Forward declarations at global scope — a specialization names the type by its
// real fully-qualified spelling, which only works if the declaration is there
// and not nested inside the reflection namespace.
{forwards}

namespace Assisi::Core::Reflect
{{

{body}
}} // namespace Assisi::Core::Reflect
"""


def check_message_handlers(headers) -> str:
    """One handler per message type, checked across the whole tree.

    Two modules each claiming the same message would otherwise be resolved by
    link order — which is to say by accident, differently on different
    platforms, and silently. Whole-tree is the only scope at which the question
    is meaningful, which is why this is a separate pass from the per-header
    codegen that emits the bindings themselves.

    Returns a human-readable summary; raises on a duplicate, naming both sites.
    """
    messages_by_fqn, handlers = collect_messages_and_handlers(headers)

    bound: dict = {}
    for handler in sorted(handlers, key=lambda h: (h.header, h.name)):
        message_fqn = _resolve_message_type(handler, messages_by_fqn, Path(handler.header).name)
        if message_fqn in bound:
            first = bound[message_fqn]
            raise ValueError(
                f"two handlers are declared for message '{message_fqn.lstrip(':')}':\n"
                f"  {first.fqn} in {first.header}\n"
                f"  {handler.fqn} in {handler.header}\n"
                f"A message type has exactly one handler. Two would be resolved by link order, "
                f"which is to say by accident.")
        bound[message_fqn] = handler

    lines = [f'{len(messages_by_fqn)} message type(s), {len(bound)} handler(s)']
    for message_fqn, handler in sorted(bound.items()):
        lines.append(f'  {message_fqn.lstrip(":")} -> {handler.fqn.lstrip(":")}')
    # Not an error. A message nobody handles is a normal state — one side of the
    # wire may simply not care about it — and it is dropped and counted at
    # dispatch. Listing it is how someone notices a handler they meant to write,
    # without the build refusing to proceed over a decision that is theirs.
    for fqn in sorted(set(messages_by_fqn) - {f.lstrip(':') for f in bound}):
        lines.append(f'  {fqn} -> (no handler)')

    lines.extend(check_systems(headers))
    return '\n'.join(lines) + '\n'


def check_systems(headers) -> list:
    """Duplicate names, dangling after/before, and ordering cycles — whole-tree.

    All three are only answerable at this scope: a name is what a *file* says, so
    two modules claiming it collide no matter which one a level loads, and an
    `after` naming a system in a module this build did not link is a level that
    installs a system that never runs. The alternative to catching them here is
    catching them as a level that quietly does nothing.
    """
    systems: list = []
    for header in headers:
        try:
            systems.extend(parse_header_systems(Path(header).resolve()))
        except ValueError:
            raise
        except Exception:
            # A header that will not parse is already a hard error in the
            # per-header pass; repeating it here would bury the real message.
            continue

    by_name: dict = {}
    for system in sorted(systems, key=lambda s: (s.header, s.function)):
        if system.name in by_name:
            first = by_name[system.name]
            raise ValueError(
                f"two systems are named '{system.name}':\n"
                f"  {first.fqn} in {first.header}\n"
                f"  {system.fqn} in {system.header}\n"
                f"A file names a system by this string, so two of them cannot be told apart. Give one "
                f"an explicit ASYSTEM(..., name = \"...\").")
        by_name[system.name] = system

    # Edges: after means "this runs later", before means "this runs earlier".
    # Both are checked against the whole tree, because an ordering constraint on a
    # system nobody declares is a constraint that will never be honoured.
    edges: dict = {name: set() for name in by_name}
    for system in systems:
        for target in system.after + system.before:
            if target not in by_name:
                raise ValueError(
                    f"{Path(system.header).name}: system '{system.name}' orders itself against "
                    f"'{target}', which no ASYSTEM declares. An ordering constraint naming nothing is "
                    f"silently no constraint at all.")
        for target in system.after:
            edges[system.name].add(target)   # target runs first
        for target in system.before:
            edges[target].add(system.name)   # this one runs first

    # Depth-first with a colour mark: grey means "on the current path", which is
    # exactly a cycle when we meet it again.
    WHITE, GREY, BLACK = 0, 1, 2
    colour = {name: WHITE for name in by_name}

    def visit(name: str, path: list) -> None:
        colour[name] = GREY
        for dependency in sorted(edges[name]):
            if colour[dependency] == GREY:
                loop = path[path.index(dependency):] if dependency in path else [dependency]
                raise ValueError(
                    f"systems order themselves in a cycle: {' -> '.join(loop + [dependency])}. "
                    f"No execution order satisfies it, so one of the after/before pairs has to go.")
            if colour[dependency] == WHITE:
                visit(dependency, path + [dependency])
        colour[name] = BLACK

    for name in sorted(by_name):
        if colour[name] == WHITE:
            visit(name, [name])

    lines = [f'{len(by_name)} system(s)']
    for name, system in sorted(by_name.items()):
        lines.append(f'  {name} [{system.phase}] -> {system.fqn.lstrip(":")}')
    return lines


def main():
    parser = argparse.ArgumentParser(description='Assisi reflection code generator')
    parser.add_argument('headers', nargs='+', type=Path,
                        help='Header file(s) to process')
    parser.add_argument('--outdir', type=Path,
                        help='Output directory for .generated.cpp files')
    parser.add_argument('--include', dest='include_path', default=None,
                        help='Override #include path in generated file '
                             '(auto-detected from include/ segment if omitted)')
    parser.add_argument('--count-replicable', dest='count_out', type=Path, default=None,
                        help='Instead of generating registrations, count ACOMP(replicable) '
                             'types across every header given and write ReplicableLimits.hpp '
                             'to this path.')
    parser.add_argument('--message-traits', dest='traits_out', type=Path, default=None,
                        help='Instead of generating registrations, write the compile-time '
                             'MessageTraits header for every AMSG across the headers given.')
    parser.add_argument('--check-handlers', dest='check_out', type=Path, default=None,
                        help='Instead of generating registrations, check that no message type '
                             'has two AMSG_HANDLER declarations across every header given, and '
                             'write the handler map to this path.')
    args = parser.parse_args()

    if args.traits_out is not None:
        args.traits_out.parent.mkdir(parents=True, exist_ok=True)
        try:
            text = render_message_traits(args.headers)
        except Exception as error:
            print(f'reflectgen: error: {error}', file=sys.stderr)
            sys.exit(1)
        args.traits_out.write_text(text, encoding='utf-8')
        print(f'reflectgen: {text.count("struct MessageTraits<")} message trait(s) -> {args.traits_out}')
        sys.exit(0)

    if args.check_out is not None:
        args.check_out.parent.mkdir(parents=True, exist_ok=True)
        try:
            text = check_message_handlers(args.headers)
        except Exception as error:
            print(f'reflectgen: error: {error}', file=sys.stderr)
            sys.exit(1)
        args.check_out.write_text(text, encoding='utf-8')
        print(f'reflectgen: {text.splitlines()[0]}')
        sys.exit(0)

    if args.count_out is not None:
        args.count_out.parent.mkdir(parents=True, exist_ok=True)
        count = count_replicable(args.headers)
        args.count_out.write_text(render_replicable_limits(count), encoding='utf-8')
        print(f'reflectgen: {count} replicable component type(s) -> {args.count_out}')
        sys.exit(0)

    if args.outdir is None:
        parser.error('--outdir is required unless --count-replicable is given')

    args.outdir.mkdir(parents=True, exist_ok=True)

    ok = True
    for header in args.headers:
        header = header.resolve()
        include_path = args.include_path or _detect_include_path(header)

        print(f'reflectgen: {header.name} -> {include_path}')
        # generate_cpp runs inside the try because it is where the rest of
        # default-deny lives (asset EntityRefs, the replication annotations): a
        # rejected header should print the reason it was rejected, not a Python
        # traceback with the reason buried at the bottom.
        try:
            components, messages, handlers = parse_header_full(header)
            systems = parse_header_systems(header)
            _check_unsupported(components, header.name)

            if not components and not messages and not handlers and not systems:
                # Still write the file, empty. The build declares this path as an
                # output, so producing nothing turns a header that legitimately
                # registers nothing — a handler-only header, say — into a missing
                # file and a confusing compile error somewhere downstream.
                print(f'  (no ACOMP or AMSG annotations found — writing an empty registration unit)')
                out = args.outdir / (header.stem + '.generated.cpp')
                out.write_text(f'// AUTO-GENERATED by reflectgen — do not edit.\n'
                               f'// Source: {include_path}\n'
                               f'//\n'
                               f'// This header declares nothing that registers. AMSG_HANDLER declarations\n'
                               f'// are bound by the whole-tree pass instead (--message-handlers), so a\n'
                               f'// handler-only header lands here empty and that is correct.\n',
                               encoding='utf-8')
                print(f'  wrote: {out}')
                continue

            for comp in components:
                print(f'  found: {comp.name} ({len(comp.fields)} field(s))')
            for msg in messages:
                print(f'  found: {msg.name} (message, {msg.direction}/{msg.reliability}, '
                      f'{len(msg.fields)} field(s))')
            for handler in handlers:
                print(f'  found: {handler.name} (handler for {handler.message})')
            for system in systems:
                print(f'  found: {system.name} (system, {system.phase})')

            cpp = generate_cpp(components, include_path, messages, handlers, systems)
        except Exception as e:
            print(f'  error: {e}', file=sys.stderr)
            ok = False
            continue

        out = args.outdir / (header.stem + '.generated.cpp')
        out.write_text(cpp, encoding='utf-8')
        print(f'  wrote: {out}')

    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
