#!/usr/bin/env python3
"""reflectgen.py — Assisi Reflection Code Generator (CLI entry point)

Scans C++ headers for ACOMP/AFIELD annotations and emits .generated.cpp files
that register each component with Assisi::Core::Reflect::ComponentRegistry.

Usage:
    python reflectgen.py <header> [<header> ...] --outdir <dir> [--include <path>]

    <header>         Absolute or relative path to the source header.
    --outdir <dir>   Directory to write .generated.cpp files into.
    --include <path> Override the #include path written into generated files.
                     If omitted, auto-detected from the 'include/' segment in
                     the header path (e.g. '.../include/Assisi/Foo/Bar.hpp'
                     becomes 'Assisi/Foo/Bar.hpp').

The implementation is split across three sibling modules; this file is the CLI
plus a stable facade that re-exports their public surface so `import reflectgen`
keeps working for callers and tests:

    reflect_types    the C++ type -> codegen mapping (TYPES, TypeCodegen, ...)
    reflect_parser   header scanning + the parse-time data model
    reflect_codegen  emission of the .generated.cpp registration code
"""

import sys
import argparse
from pathlib import Path

# Re-export the public surface so `reflectgen.X` resolves for every existing
# caller and the test-suite (which reaches in for parse_header, generate_cpp,
# the dataclasses, UNSUPPORTED_TYPES, _check_unsupported, _detect_include_path).
from reflect_types import (  # noqa: F401
    TypeCodegen,
    TYPES,
    UNSUPPORTED_TYPES,
    _ASSET_ID_TYPES,
    _ENTITY_REF_TYPES,
)
from reflect_parser import (  # noqa: F401
    AnnotArgs,
    EnumInfo,
    RadioInfo,
    FieldInfo,
    ComponentInfo,
    parse_header,
    parse_annot_args,
    parse_radio_spec,
    parse_enum_constants,
    strip_comments,
    _detect_include_path,
)
from reflect_codegen import (  # noqa: F401
    generate_cpp,
    _check_unsupported,
    _check_asset_fields,
    _check_replication,
    _field_tc,
    NUMERIC_BOUND_RANGES,
)


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────

def count_replicable(headers) -> int:
    """How many ACOMP(replicable) component types exist across @p headers.

    A whole-tree question asked once, unlike the per-header code generation
    everywhere else here: the answer sizes ComponentMask, the exclusion bitset on
    the Replicated marker, whose bit index is a component's ordinal among the
    replicable types. Sizing it from an actual count rather than a configured
    ceiling is what keeps that a detail nobody has to know about.

    Deliberately tolerant of headers it cannot parse: a malformed one is already
    a hard error in the per-header pass, and duplicating that failure here would
    only bury the real message under a second, worse-located one.
    """
    total = 0
    for header in headers:
        try:
            components = parse_header(Path(header).resolve())
        except Exception:
            continue
        total += sum(1 for c in components
                     if c.args.has('replicable') and not c.is_asset and not c.args.has('transient'))
    return total


def render_replicable_limits(count: int) -> str:
    """The generated header that fixes ComponentMask's width."""
    mask_bytes = max(1, (count + 7) // 8)
    return f"""\
/* Generated by reflectgen. Do not edit. */
#pragma once

/// @file ReplicableLimits.hpp
/// @brief How wide a ComponentMask must be, counted from the tree at build time.
///
/// The count is of ACOMP(replicable) component types across every header routed
/// through assisi_reflect(). It sizes the exclusion bitset on NetSync's
/// Replicated marker, whose bit index is a component's ordinal among the
/// replicable types (ComponentRegistry::ReplicableOrdinalOf).
///
/// Byte granularity, so a worst case wastes seven bits rather than sixty-three,
/// and so the value only *changes* on a byte boundary — the build wraps this in
/// copy_if_different, which means most header edits regenerate an identical file
/// and rebuild nothing.
///
/// Nothing here ever reaches a file or a socket: masks serialize as arrays of
/// component *names*, on disk and on the wire alike. Widening this is therefore
/// a recompile and never a migration.

#include <cstddef>

namespace Assisi::Core::Reflect
{{

/// ACOMP(replicable) component types found in this build.
inline constexpr std::size_t kReplicableComponentCount = {count};

/// Bytes a ComponentMask needs to hold one bit per the above. At least one, so
/// a build with no replicable components still yields a valid array.
inline constexpr std::size_t kReplicableMaskBytes = {mask_bytes};

}} // namespace Assisi::Core::Reflect
"""


def main():
    parser = argparse.ArgumentParser(description='Assisi reflection code generator')
    parser.add_argument('headers', nargs='+', type=Path,
                        help='Header file(s) to process')
    parser.add_argument('--outdir', type=Path,
                        help='Output directory for .generated.cpp files')
    parser.add_argument('--include', dest='include_path', default=None,
                        help='Override #include path in generated file '
                             '(auto-detected from include/ segment if omitted)')
    parser.add_argument('--count-replicable', dest='count_out', type=Path, default=None,
                        help='Instead of generating registrations, count ACOMP(replicable) '
                             'types across every header given and write ReplicableLimits.hpp '
                             'to this path.')
    args = parser.parse_args()

    if args.count_out is not None:
        args.count_out.parent.mkdir(parents=True, exist_ok=True)
        count = count_replicable(args.headers)
        args.count_out.write_text(render_replicable_limits(count), encoding='utf-8')
        print(f'reflectgen: {count} replicable component type(s) -> {args.count_out}')
        sys.exit(0)

    if args.outdir is None:
        parser.error('--outdir is required unless --count-replicable is given')

    args.outdir.mkdir(parents=True, exist_ok=True)

    ok = True
    for header in args.headers:
        header = header.resolve()
        include_path = args.include_path or _detect_include_path(header)

        print(f'reflectgen: {header.name} -> {include_path}')
        # generate_cpp runs inside the try because it is where the rest of
        # default-deny lives (asset EntityRefs, the replication annotations): a
        # rejected header should print the reason it was rejected, not a Python
        # traceback with the reason buried at the bottom.
        try:
            components = parse_header(header)
            _check_unsupported(components, header.name)

            if not components:
                print(f'  (no ACOMP annotations found, skipping)')
                continue

            for comp in components:
                print(f'  found: {comp.name} ({len(comp.fields)} field(s))')

            cpp = generate_cpp(components, include_path)
        except Exception as e:
            print(f'  error: {e}', file=sys.stderr)
            ok = False
            continue

        out = args.outdir / (header.stem + '.generated.cpp')
        out.write_text(cpp, encoding='utf-8')
        print(f'  wrote: {out}')

    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
