// AUTO-GENERATED by reflectgen — do not edit.
// Source: Assisi/Testing/Sample.hpp

#include <Assisi/Core/Reflect/ComponentRegistry.hpp>
#include <Assisi/ECS/Scene.hpp>
#include <Assisi/Runtime/SceneSerializer.hpp>
#include <cstdint>
#include <Assisi/Testing/Sample.hpp>

namespace
{
// ── SampleAllTypes ────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleAllTypes = []() -> bool
{
    using T = Assisi::Runtime::SampleAllTypes;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleAllTypes",
        typeid(T),
        {
            { "f", Assisi::Core::Reflect::FieldType::Float, offsetof(T, f), false, false },
            { "d", Assisi::Core::Reflect::FieldType::Double, offsetof(T, d), false, false },
            { "i32", Assisi::Core::Reflect::FieldType::Int32, offsetof(T, i32), false, false },
            { "u32", Assisi::Core::Reflect::FieldType::UInt32, offsetof(T, u32), false, false },
            { "i64", Assisi::Core::Reflect::FieldType::Int64, offsetof(T, i64), false, false },
            { "u64", Assisi::Core::Reflect::FieldType::UInt64, offsetof(T, u64), false, false },
            { "flag", Assisi::Core::Reflect::FieldType::Bool, offsetof(T, flag), false, false },
            { "shape", Assisi::Core::Reflect::FieldType::Enum, offsetof(T, shape), false, false, false, false, 0.f, 0.f, { { "Box", 0 }, { "Sphere", 1 }, { "Capsule", 5 }, { "Cylinder", 6 } }, 4, false },
            { "v2", Assisi::Core::Reflect::FieldType::Vec2, offsetof(T, v2), false, false },
            { "v3", Assisi::Core::Reflect::FieldType::Vec3, offsetof(T, v3), false, false },
            { "v4", Assisi::Core::Reflect::FieldType::Vec4, offsetof(T, v4), false, false },
            { "q", Assisi::Core::Reflect::FieldType::Quat, offsetof(T, q), false, false },
            { "m", Assisi::Core::Reflect::FieldType::Mat4, offsetof(T, m), false, false },
            { "assetPath", Assisi::Core::Reflect::FieldType::AssetPath, offsetof(T, assetPath), false, false },
            { "label", Assisi::Core::Reflect::FieldType::String, offsetof(T, label), false, false },
            { "paths", Assisi::Core::Reflect::FieldType::AssetPathVector, offsetof(T, paths), false, false },
            { "runtimeCache", Assisi::Core::Reflect::FieldType::Float, offsetof(T, runtimeCache), true, false }
        },
        [](const void* ptr) -> nlohmann::json
        {
            const auto& c = *static_cast<const T*>(ptr);
            return nlohmann::json{
                { "f", c.f },
                { "d", c.d },
                { "i32", c.i32 },
                { "u32", c.u32 },
                { "i64", c.i64 },
                { "u64", c.u64 },
                { "flag", c.flag },
                { "shape", static_cast<std::int64_t>(c.shape) },
                { "v2", { c.v2.x, c.v2.y } },
                { "v3", { c.v3.x, c.v3.y, c.v3.z } },
                { "v4", { c.v4.x, c.v4.y, c.v4.z, c.v4.w } },
                { "q", { c.q.w, c.q.x, c.q.y, c.q.z } },
                { "m", { c.m[0][0], c.m[0][1], c.m[0][2], c.m[0][3], c.m[1][0], c.m[1][1], c.m[1][2], c.m[1][3], c.m[2][0], c.m[2][1], c.m[2][2], c.m[2][3], c.m[3][0], c.m[3][1], c.m[3][2], c.m[3][3] } },
                { "assetPath", std::string(c.assetPath.View()) },
                { "label", std::string(c.label.View()) },
                { "paths", [&]{ nlohmann::json _arr = nlohmann::json::array(); for (const auto& _p : c.paths) _arr.push_back(std::string(_p.View())); return _arr; }() },
            };
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            if (j.contains("f")) comp.f = j.at("f").get<float>();
            if (j.contains("d")) comp.d = j.at("d").get<double>();
            if (j.contains("i32")) comp.i32 = j.at("i32").get<int32_t>();
            if (j.contains("u32")) comp.u32 = j.at("u32").get<uint32_t>();
            if (j.contains("i64")) comp.i64 = j.at("i64").get<int64_t>();
            if (j.contains("u64")) comp.u64 = j.at("u64").get<uint64_t>();
            if (j.contains("flag")) comp.flag = j.at("flag").get<bool>();
            if (j.contains("shape")) comp.shape = static_cast<Assisi::Runtime::SampleShape>(j.at("shape").get<std::int64_t>());
            { if (j.contains("v2")) { const auto& _v = j.at("v2"); comp.v2 = { _v[0].get<float>(), _v[1].get<float>() }; } }
            { if (j.contains("v3")) { const auto& _v = j.at("v3"); comp.v3 = { _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>() }; } }
            { if (j.contains("v4")) { const auto& _v = j.at("v4"); comp.v4 = { _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>(), _v[3].get<float>() }; } }
            { if (j.contains("q")) { const auto& _v = j.at("q"); comp.q = glm::quat{ _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>(), _v[3].get<float>() }; } }
            { if (j.contains("m")) { const auto& _v = j.at("m"); comp.m = glm::mat4{ _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>(), _v[3].get<float>(), _v[4].get<float>(), _v[5].get<float>(), _v[6].get<float>(), _v[7].get<float>(), _v[8].get<float>(), _v[9].get<float>(), _v[10].get<float>(), _v[11].get<float>(), _v[12].get<float>(), _v[13].get<float>(), _v[14].get<float>(), _v[15].get<float>() }; } }
            { if (j.contains("assetPath")) comp.assetPath.Assign(j.at("assetPath").get<std::string>()); }
            { if (j.contains("label")) comp.label.Assign(j.at("label").get<std::string>()); }
            { if (j.contains("paths")) { comp.paths.clear(); for (const auto& _e : j.at("paths")) { Assisi::Core::AssetPath _p; _p.Assign(_e.get<std::string>()); comp.paths.push_back(_p); } } }
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // Scene::Add rejects a duplicate rather than replacing it, so an
            // entity that already has this component is reset in place. Both
            // paths stamp the change tick for a tracked type.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            if (T* existing = scene.GetMut<T>(e))
            {
                *existing = T{};
                return existing;
            }
            return scene.Add<T>(e, T{});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // GetMut, not Get: this is the writing accessor, so it stamps.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.GetMut<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true,      // serializable
        true       // tracksChanges
    });
    return true;
}();

// ── SampleRef ─────────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleRef = []() -> bool
{
    using T = Assisi::Runtime::SampleRef;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleRef",
        typeid(T),
        {
            { "target", Assisi::Core::Reflect::FieldType::EntityRef, offsetof(T, target), false, false }
        },
        [](const void* ptr) -> nlohmann::json
        {
            const auto& c = *static_cast<const T*>(ptr);
            return nlohmann::json{
                { "target", Assisi::Runtime::SceneSerializer::EntityToRef(c.target) },
            };
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            { if (j.contains("target")) { comp.target = Assisi::Runtime::SceneSerializer::RefToEntity(j.at("target")); } else { comp.target = Assisi::ECS::NullEntity; } }
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // Scene::Add rejects a duplicate rather than replacing it, so an
            // entity that already has this component is reset in place. Both
            // paths stamp the change tick for a tracked type.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            if (T* existing = scene.GetMut<T>(e))
            {
                *existing = T{};
                return existing;
            }
            return scene.Add<T>(e, T{});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // GetMut, not Get: this is the writing accessor, so it stamps.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.GetMut<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true       // serializable
    });
    return true;
}();

// ── SampleEmpty ───────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleEmpty = []() -> bool
{
    using T = Assisi::Runtime::SampleEmpty;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleEmpty",
        typeid(T),
        {
            
        },
        [](const void* ptr) -> nlohmann::json
        {
            (void)ptr;
            return nlohmann::json{};
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            (void)j;
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // Scene::Add rejects a duplicate rather than replacing it, so an
            // entity that already has this component is reset in place. Both
            // paths stamp the change tick for a tracked type.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            if (T* existing = scene.GetMut<T>(e))
            {
                *existing = T{};
                return existing;
            }
            return scene.Add<T>(e, T{});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // GetMut, not Get: this is the writing accessor, so it stamps.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.GetMut<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true       // serializable
    });
    return true;
}();

// ── SampleTransient ───────────────────────────────────────────────────────────
// ACOMP(transient): id-only registration, not serialized.
static const bool _reflectgen_SampleTransient = []() -> bool
{
    using T = Assisi::Runtime::SampleTransient;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleTransient",
        typeid(T),
        {},      // fields: none reflected
        nullptr,   // serialize
        nullptr,   // addToScene
        nullptr,   // iterateEntities
        nullptr,   // getByEntity
        nullptr,   // construct
        nullptr,   // getMutable
        false      // serializable
    });
    return true;
}();

// ── SampleRadio ───────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleRadio = []() -> bool
{
    using T = Assisi::Runtime::SampleRadio;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleRadio",
        typeid(T),
        {
            { "mode", Assisi::Core::Reflect::FieldType::Enum, offsetof(T, mode), false, false, false, false, 0.f, 0.f, { { "Off", 0 }, { "Low", 1 }, { "High", 2 } }, 1, false },
            { "intensity", Assisi::Core::Reflect::FieldType::Float, offsetof(T, intensity), false, false, false, false, 0.f, 0.f, {}, 0, false, "mode", { 2 }, Assisi::Core::Reflect::RadioBehavior::Vanish },
            { "sub", Assisi::Core::Reflect::FieldType::Enum, offsetof(T, sub), false, false, false, false, 0.f, 0.f, { { "A", 0 }, { "B", 1 } }, 4, true, "mode", { 1, 2 }, Assisi::Core::Reflect::RadioBehavior::Vanish },
            { "level", Assisi::Core::Reflect::FieldType::Int32, offsetof(T, level), false, false, true, false, 0.0f, 0.f, {}, 0, false, "sub", { 1 }, Assisi::Core::Reflect::RadioBehavior::Grey }
        },
        [](const void* ptr) -> nlohmann::json
        {
            const auto& c = *static_cast<const T*>(ptr);
            return nlohmann::json{
                { "mode", static_cast<std::int64_t>(c.mode) },
                { "intensity", c.intensity },
                { "sub", static_cast<std::int64_t>(c.sub) },
                { "level", c.level },
            };
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            if (j.contains("mode")) comp.mode = static_cast<Assisi::Runtime::SampleMode>(j.at("mode").get<std::int64_t>());
            if (j.contains("intensity")) comp.intensity = j.at("intensity").get<float>();
            if (j.contains("sub")) comp.sub = static_cast<Assisi::Runtime::SampleSub>(j.at("sub").get<std::int64_t>());
            if (j.contains("level")) comp.level = j.at("level").get<int32_t>();
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // Scene::Add rejects a duplicate rather than replacing it, so an
            // entity that already has this component is reset in place. Both
            // paths stamp the change tick for a tracked type.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            if (T* existing = scene.GetMut<T>(e))
            {
                *existing = T{};
                return existing;
            }
            return scene.Add<T>(e, T{});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // GetMut, not Get: this is the writing accessor, so it stamps.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.GetMut<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true       // serializable
    });
    return true;
}();

// ── SampleReplicated ──────────────────────────────────────────────────────────
static const bool _reflectgen_SampleReplicated = []() -> bool
{
    using T = Assisi::Runtime::SampleReplicated;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleReplicated",
        typeid(T),
        {
            { "shared", Assisi::Core::Reflect::FieldType::Float, offsetof(T, shared), false, false },
            { "serverOnly", Assisi::Core::Reflect::FieldType::Int32, offsetof(T, serverOnly), false, true }
        },
        [](const void* ptr) -> nlohmann::json
        {
            const auto& c = *static_cast<const T*>(ptr);
            return nlohmann::json{
                { "shared", c.shared },
                { "serverOnly", c.serverOnly },
            };
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            if (j.contains("shared")) comp.shared = j.at("shared").get<float>();
            if (j.contains("serverOnly")) comp.serverOnly = j.at("serverOnly").get<int32_t>();
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // Scene::Add rejects a duplicate rather than replacing it, so an
            // entity that already has this component is reset in place. Both
            // paths stamp the change tick for a tracked type.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            if (T* existing = scene.GetMut<T>(e))
            {
                *existing = T{};
                return existing;
            }
            return scene.Add<T>(e, T{});
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> void*
        {
            // GetMut, not Get: this is the writing accessor, so it stamps.
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.GetMut<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true,      // serializable
        true,      // tracksChanges
        true       // replicable
    });
    return true;
}();

} // namespace
