// AUTO-GENERATED by reflectgen — do not edit.
// Source: Assisi/Testing/Sample.hpp

#include <Assisi/Core/Reflect/ComponentRegistry.hpp>
#include <Assisi/ECS/Scene.hpp>
#include <Assisi/Runtime/SceneSerializer.hpp>
#include <Assisi/Testing/Sample.hpp>

namespace
{
// ── SampleAllTypes ────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleAllTypes = []() -> bool
{
    using T = Assisi::Runtime::SampleAllTypes;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleAllTypes",
        typeid(T),
        {
            { "f", Assisi::Core::Reflect::FieldType::Float, offsetof(T, f), false },
            { "d", Assisi::Core::Reflect::FieldType::Double, offsetof(T, d), false },
            { "i", Assisi::Core::Reflect::FieldType::Int, offsetof(T, i), false },
            { "i32", Assisi::Core::Reflect::FieldType::Int32, offsetof(T, i32), false },
            { "u32", Assisi::Core::Reflect::FieldType::UInt32, offsetof(T, u32), false },
            { "flag", Assisi::Core::Reflect::FieldType::Bool, offsetof(T, flag), false },
            { "v2", Assisi::Core::Reflect::FieldType::Vec2, offsetof(T, v2), false },
            { "v3", Assisi::Core::Reflect::FieldType::Vec3, offsetof(T, v3), false },
            { "v4", Assisi::Core::Reflect::FieldType::Vec4, offsetof(T, v4), false },
            { "q", Assisi::Core::Reflect::FieldType::Quat, offsetof(T, q), false },
            { "m", Assisi::Core::Reflect::FieldType::Mat4, offsetof(T, m), false },
            { "assetPath", Assisi::Core::Reflect::FieldType::AssetPath, offsetof(T, assetPath), false },
            { "runtimeCache", Assisi::Core::Reflect::FieldType::Float, offsetof(T, runtimeCache), true }
        },
        [](const void* ptr) -> nlohmann::json
        {
            const auto& c = *static_cast<const T*>(ptr);
            return nlohmann::json{
                { "f", c.f },
                { "d", c.d },
                { "i", c.i },
                { "i32", c.i32 },
                { "u32", c.u32 },
                { "flag", c.flag },
                { "v2", { c.v2.x, c.v2.y } },
                { "v3", { c.v3.x, c.v3.y, c.v3.z } },
                { "v4", { c.v4.x, c.v4.y, c.v4.z, c.v4.w } },
                { "q", { c.q.w, c.q.x, c.q.y, c.q.z } },
                { "m", { c.m[0][0], c.m[0][1], c.m[0][2], c.m[0][3], c.m[1][0], c.m[1][1], c.m[1][2], c.m[1][3], c.m[2][0], c.m[2][1], c.m[2][2], c.m[2][3], c.m[3][0], c.m[3][1], c.m[3][2], c.m[3][3] } },
                { "assetPath", std::string(c.assetPath.View()) },
            };
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            if (j.contains("f")) comp.f = j.at("f").get<float>();
            if (j.contains("d")) comp.d = j.at("d").get<double>();
            if (j.contains("i")) comp.i = j.at("i").get<int>();
            if (j.contains("i32")) comp.i32 = j.at("i32").get<int32_t>();
            if (j.contains("u32")) comp.u32 = j.at("u32").get<uint32_t>();
            if (j.contains("flag")) comp.flag = j.at("flag").get<bool>();
            { if (j.contains("v2")) { const auto& _v = j.at("v2"); comp.v2 = { _v[0].get<float>(), _v[1].get<float>() }; } }
            { if (j.contains("v3")) { const auto& _v = j.at("v3"); comp.v3 = { _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>() }; } }
            { if (j.contains("v4")) { const auto& _v = j.at("v4"); comp.v4 = { _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>(), _v[3].get<float>() }; } }
            { if (j.contains("q")) { const auto& _v = j.at("q"); comp.q = glm::quat{ _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>(), _v[3].get<float>() }; } }
            { if (j.contains("m")) { const auto& _v = j.at("m"); comp.m = glm::mat4{ _v[0].get<float>(), _v[1].get<float>(), _v[2].get<float>(), _v[3].get<float>(), _v[4].get<float>(), _v[5].get<float>(), _v[6].get<float>(), _v[7].get<float>(), _v[8].get<float>(), _v[9].get<float>(), _v[10].get<float>(), _v[11].get<float>(), _v[12].get<float>(), _v[13].get<float>(), _v[14].get<float>(), _v[15].get<float>() }; } }
            { if (j.contains("assetPath")) comp.assetPath.Assign(j.at("assetPath").get<std::string>()); }
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true,      // serializable
        true       // tracksChanges
    });
    return true;
}();

// ── SampleRef ─────────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleRef = []() -> bool
{
    using T = Assisi::Runtime::SampleRef;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleRef",
        typeid(T),
        {
            { "target", Assisi::Core::Reflect::FieldType::EntityRef, offsetof(T, target), false }
        },
        [](const void* ptr) -> nlohmann::json
        {
            const auto& c = *static_cast<const T*>(ptr);
            return nlohmann::json{
                { "target", (c.target != Assisi::ECS::NullEntity ? nlohmann::json(Assisi::Runtime::SceneSerializer::EntityToIndex(c.target).value_or(~0u)) : nlohmann::json(nullptr)) },
            };
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            { if (j.contains("target") && !j.at("target").is_null()) { comp.target = Assisi::Runtime::SceneSerializer::IndexToEntity(j.at("target").get<uint32_t>()); } else { comp.target = Assisi::ECS::NullEntity; } }
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true       // serializable
    });
    return true;
}();

// ── SampleEmpty ───────────────────────────────────────────────────────────────
static const bool _reflectgen_SampleEmpty = []() -> bool
{
    using T = Assisi::Runtime::SampleEmpty;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleEmpty",
        typeid(T),
        {
            
        },
        [](const void* ptr) -> nlohmann::json
        {
            (void)ptr;
            return nlohmann::json{};
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen, const nlohmann::json& j)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            Assisi::ECS::Entity e{entity_index, entity_gen};
            T comp{};
            (void)j;
            (void)scene.Add(e, comp);
        },
        [](void* scene_ptr, std::function<void(uint32_t, uint32_t, const void*)> cb)
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            for (auto [e, comp] : scene.Query<T>())
                cb(e.index, e.generation, &comp);
        },
        [](void* scene_ptr, uint32_t entity_index, uint32_t entity_gen) -> const void*
        {
            auto& scene = *static_cast<Assisi::ECS::Scene*>(scene_ptr);
            return scene.Get<T>(Assisi::ECS::Entity{entity_index, entity_gen});
        },
        true       // serializable
    });
    return true;
}();

// ── SampleTransient ───────────────────────────────────────────────────────────
// ACOMP(transient): id-only registration, not serialized.
static const bool _reflectgen_SampleTransient = []() -> bool
{
    using T = Assisi::Runtime::SampleTransient;
    Assisi::Core::Reflect::ComponentRegistry::Instance().Register({
        "SampleTransient",
        typeid(T),
        {},      // fields: none reflected
        nullptr,   // serialize
        nullptr,   // addToScene
        nullptr,   // iterateEntities
        nullptr,   // getByEntity
        false      // serializable
    });
    return true;
}();

} // namespace
