/* Copyright (c) 2025 Francisco Vivas Puerto (aka "DaFrancc"). */
#pragma once

/// @file BlueNoise.hpp
/// @brief The blue-noise tile shadow filters rotate their disks by.
///
/// Neighbouring texels hold very different values, so a filter rotated by them
/// leaves fine grain rather than the blotches white noise leaves or the pattern
/// a repeating lattice prints — and a spatial filter with no history to average
/// over is exactly the case where that difference shows. Generated by
/// scripts/gen_blue_noise.py and committed.

#include <cstdint>
#include <span>

namespace Assisi::Render
{

/// @brief Side of the tile, in texels. It repeats across the screen.
inline constexpr std::uint32_t kBlueNoiseTileSize = 64;

/// @brief The tile, row by row: one 8-bit rank per texel, every value in
/// [0, 255] appearing equally often.
[[nodiscard]] std::span<const std::uint8_t> BlueNoiseTile();

} // namespace Assisi::Render
